spring:
  application:
    name: springNote

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/local
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update   # 스키마 자동 생성
      show_sql: true
      format_sql: true   # SQL 출력 포맷팅
    show-sql: true       # JPA 쿼리 로그 출력


server:
  port: 8081
  servlet:
    context-path: /
